spring.application.name=o-que-vamos-assistir-hoje-api

spring.datasource.url=jdbc:postgresql://localhost:5432/oqvah_db
spring.datasource.username=oqvah_user
spring.datasource.password=oqvah_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
